
-- use  CUSTOMER5
-- DROP TABLE IF EXISTS  "CUSTOMER5"."WEBRULE";  -- does not work
-- DROP TABLE "CUSTOMER5"."WEBRULE";

-- create schema CUSTOMER5;

CREATE TABLE "CUSTOMER5".WEBRULE (
 "RULETYPE"   VARCHAR (10)     NOT NULL  ,
 "RULEID"     VARCHAR (25)     NOT NULL  ,
 "RULENAME"   VARCHAR (25)     NOT NULL  ,
 "RULEVALUE"  VARCHAR (50)     NOT NULL  ,
  PRIMARY KEY ("RULETYPE", "RULEID", "RULENAME")
);

TRUNCATE TABLE "CUSTOMER5"."WEBRULE";
INSERT INTO "CUSTOMER5"."WEBRULE" VALUES( 'CM','PRDTA-12345','BusinessRule1','Allow Admin Access');
INSERT INTO "CUSTOMER5"."WEBRULE" VALUES( 'DM','PRDTA-67890','BusinessRule2','Allow User Access');



-- call _SYS_REPO.GRANT_ACTIVATED_ROLE('p2000584808trial.customer5::user', 'p2000584808');

-- call _SYS_REPO.GRANT_ACTIVATED_ROLE('customer5::user', 'p2000584808');










